### ISSUE TITLE
Still showing steam name, not RP names.

### ISSUE THREAD

**Issue by Waterrkko1** [N0BODY2/chat#1]
I edited in config to use RP names but it's not working.
It's still showing steam names

**Comment by N0BODY2** [comment]
What ESX are you using ?

**Comment by Waterrkko1** [comment]
im using es_extended 2.0.0
I also had to change something from  
TriggerEvent('es:addCommand', 'me', function(source, args, rawCommand)
to 
 RegisterCommand('me', function(source, args, rawCommand)

**Comment by Waterrkko1** [comment]
I Fixed it. I downloaded the newst version from you (15 hours ago)
Thank you for help
